### ISSUE TITLE
Passphrase is missing during decryption

### ISSUE THREAD

**Issue by kalpetros** [andcri/rustyvault#7]
If I initialize the vault using a passphrase for the private key, then during a key creation or when I want o get an existing key I get the following:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 101077092, library: "digital envelope routines", function: "EVP_DecryptFinal_ex", reason: "bad decrypt", file: "../crypto/evp/evp_enc.c", line: 583 }, Error { code: 151429221, library: "PEM routines", function: "PEM_do_header", reason: "bad decrypt", file: "../crypto/pem/pem_lib.c", line: 461 }])', src/crypto/helpers.rs:38:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is because the passphrase is not passed in the decrypt function below.
We might need to ask the user to type the passphrase when calling `rustyvault new` or `rustyvault get`.

```
pub fn decrypt(buffer: Vec<u8>) -> Result<String, std::io::Error> {
    let private = fs::read_to_string("/home/andrea/.rustyvault/rustykey")?;
    let passphrase = "";

    ...
}
```

**Comment by andcri** [comment]
Yes that should be the problem. Is this working for you if you create a key pair w/o the password?

Update:
Updated code to request password protected rsa

**Comment by kalpetros** [comment]
@andcri Yes if I create a key paid w/o a password it works fine.

**Comment by andcri** [comment]
@kalpetros with the latest pr it should also work with the password

**Comment by kalpetros** [comment]
@andcri LGTM.
